name: Build Wheels

on:
  push:
    branches: [ "wheels" ]
  pull_request:
    branches: [ "wheels" ]

env:
  CIBW_BEFORE_ALL: python -m pip install cmake; yum install boost-devel eigen3-devel; wget http://lemon.cs.elte.hu/pub/sources/lemon-1.3.1.tar.gz; tar -xzf lemon-1.3.1.tar.gz; cd lemon-1.3.1; mkdir build; cd build; cmake ..; make install; cd ../..

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v3

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==2.10.0

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse pycoloquinte

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl
